src/App.tsx, src/api/group.ts, src/components/group/pages/information/index.tsx, src/components/group/pages/information/style.ts, src/components/group/pages/member/page/index.tsx, src/components/group/pages/member/page/style.ts, src/components/group/pages/member/ui/index.tsx, src/components/group/pages/member/ui/style.ts, src/libs/getUrl.ts, src/types/group.type.ts
그룹 멤버 관리 기능을 구현합니다
_No Response_
#49
=> 🔀 :: 그룹 멤버 관리 api(#49)

src/api/group.ts, src/atoms/container.ts, src/components/group/ui/manageGroup/index.tsx, src/components/group/ui/manageGroup/style.ts, src/types/group.type.ts
그룹 생성 api를 구현합니다.
_No Response_
#51
=> 🔀 :: 그룹 생성 api(#51)

src/api/header.ts, src/components/common/header/afterLogin/index.tsx, src/components/common/header/afterLogin/style.ts, src/libs/getUrl.ts
헤더 라우팅 설정과 유저 이름을 받아오는 api를 구현합니다.
_No Response_
#50
=> 🔀 :: 헤더 라우팅 설정과 API 구현(#50)

src/api/group.ts, src/components/group/pages/information/index.tsx, src/libs/getUrl.ts
그룹삭제 api를 구현합니다.
_No Response_
#57
=> 🔀 :: 그룹삭제 api(#57)

src/App.tsx, src/components/group/pages/chatting/index.tsx, src/components/group/pages/chatting/style.ts, src/components/modals/main/group/index.tsx, src/pages/index.tsx
채팅페이지 스크롤을 구현합니다.
_No Response_
#64
=> 🔀 :: 채팅페이지 스크롤(#64)

src/App.tsx, src/components/group/pages/timer/index.tsx, src/components/group/pages/timer/item/index.tsx, src/components/group/pages/timer/item/style.ts, src/components/group/pages/timer/style.ts, src/components/group/ui/groupPageHeader/index.tsx, src/pages/GroupTimerPage.tsx, src/pages/index.tsx
타이머 페이지를 퍼블리싱 합니다.
_No Response_
#66
=> 🔀 :: 타이머 페이지 퍼블리싱(#66) 

src/api/group.ts, src/api/image.ts, src/components/common/header/afterLogin/index.tsx, src/components/common/header/afterLogin/style.ts, src/components/group/pages/information/index.tsx, src/components/group/ui/manageGroup/index.tsx, src/components/group/ui/manageGroup/style.ts, src/components/main/item/index.tsx, src/components/main/item/style.ts, src/components/main/page/index.tsx, src/components/modals/main/group/index.tsx, src/components/modals/main/group/style.ts, src/components/modals/main/passwordCheck/index.tsx, src/hooks/imageToUrl.ts, src/libs/getUrl.ts, src/types/group.type.ts
그룹 생성,수정 api를 구현합니다.
_No Response_
#68
=> 🔀 :: 그룹 생성,수정 api(#68)

package-lock.json, package.json, src/setupProxy.ts, yarn.lock
소켓프록시 설정을 합니다.
_No Response_
#72
=> 🔀 :: 소켓프록시 설정(#72)

src/components/common/header/style.ts, src/components/group/pages/chatting/index.tsx, src/components/group/pages/chatting/style.ts, src/components/group/pages/member/page/style.ts, src/components/group/ui/manageGroup/style.ts, src/components/main/item/style.ts, src/components/main/page/style.ts, src/components/modals/main/group/style.ts
emotion.js를 시멘틱 마크업으로 수정합니다.
_No Response_
#77
=> 🔀 :: 시멘틱 마크업(#77)

src/api/group.ts, src/components/group/ui/manageGroup/index.tsx, src/hooks/useImageToUrl.ts
이미지 업로드 관련 기능을 수정합니다.
_No Response_
#80
=> 🔀 :: 이미지 업로드 수정(#80)

src/api/group.ts, src/components/main/page/index.tsx, src/components/modals/main/group/index.tsx, src/types/group.type.ts
인기순, 최신순 기능을 구현합니다.
_No Response_
#82
=> 🔀 :: 인기순, 최신순 구현(#82)

src/api/user.ts, src/components/modals/my/editProfileImage/index.tsx, src/components/modals/my/editProfileImage/style.ts, src/components/my/page/index.tsx, src/libs/getUrl.ts
마이페이지에서 프로필 사진 변경 기능을 했습니다.
_No Response_
#78
=> 🔀 :: 마이페이지 프로필 사진 변경(#78)

src/api/group.ts, src/api/user.ts, src/components/modals/default/index.tsx, src/components/modals/default/style.ts, src/components/modals/my/editProfileImage/index.tsx, src/components/my/page/index.tsx, src/components/my/page/style.ts, src/libs/getUrl.ts, src/types/user.type.ts
마이페이지에서 프로필 사진이 변경이 안되는 오류, 회원탈퇴 기능이 작동하지 않는 오류 등을 수정했습니다.
_No Response_
#87
=> 🔀 :: 마이페이지 에러 수정(#87) 

src/components/main/page/index.tsx
로그인하지 않았을 때 게시물 클릭 시 로그인 페이지로 이동하는 로직으로 수정하겠습니다.
_No Response_
#89
=> 🔀 :: 로그인 페이지 이동로직 수정(#89)

src/components/modals/main/group/index.tsx
그룹 가입 시 최대 인원을 넘어가도 가입이 되는 오류를 처리합니다
_No Response_
#92
=> 🔀 :: 그룹 가입 예외처리(#92)

src/components/group/pages/information/index.tsx
그룹 삭제 시 파이어베이스에 있는 채팅 데이터를 삭제합니다.
_No Response_
#98
=> 🔀 :: 파이어베이스 데이터 예외처리(#98)

src/components/group/pages/information/index.tsx, src/components/group/pages/timer/item/index.tsx, src/components/group/pages/timer/item/style.ts, src/components/group/pages/timer/page/index.tsx, src/components/group/pages/timer/page/style.ts, src/components/group/ui/groupPageHeader/index.tsx, src/components/group/ui/manageGroup/index.tsx, src/components/main/page/index.tsx, src/components/modals/main/group/index.tsx, src/components/modals/main/passwordCheck/index.tsx, src/types/user.type.ts
그룹페이지의 타이머 API를 구현합니다
Firebase의 Realtime DB를 사용했습니다
관련 이슈 #70
=> 🔀 :: 그룹 타이머 API (#70)

src/components/my/page/index.tsx, src/components/my/page/style.ts
Mypage 관련 부분을 Refactoring 했습니다.
로컬 환경에서는 문제가 없었지만 그래도 꼼꼼히 확인 부탁 드립니다.
관련 이슈 #103
=> 🔀 :: Mypage Part Refactoring (#103) 

src/components/auth/pages/signin/index.tsx, src/components/auth/ui/layout/sections/second/index.tsx, src/components/auth/ui/layout/sections/third/index.tsx
Auth Part를 Refactoring 하며 미처 확인 못한 부분들을 다시 수정 했습니다.
수정 내용
- 로그인 과정에서 비밀번호 불일치,  회원가입 과정에서 이름 중복 시 로딩 UI가 언마운트 되지 않았던 이슈 해결
#101
=> 🔀 :: Auth Part Refactoring (#101) 

src/atoms/container.ts, src/components/group/pages/chatting/index.tsx, src/components/group/pages/create/index.tsx, src/components/group/pages/information/index.tsx, src/components/group/pages/member/page/index.tsx, src/components/group/pages/member/ui/index.tsx, src/components/group/ui/groupPageHeader/index.tsx, src/components/group/ui/manageGroup/index.tsx
Group 관련 부분을 Refactoring 합니다.
Group 관련 부분
- 그룹 생성, 수정 페이지
- 그룹 정보 페이지
- 그룹원 수정 페이지
- 채팅 페이지
- 타이머 페이지
#103
=> 🔀 :: Group Part Refactoring (#103)

src/components/group/ui/manageGroup/index.tsx
Group 관련 부분을 Refactoring 합니다.
수정 부분
- 그룹 수정 시 인원 수가 2명 이하로 설정되는 오류를 수정 했습니다.
- 그룹 설명 글자 수를 100자로 제한 했습니다.
#103
=> 🔀 :: Group Part Refactoring (#103) 
